### ISSUE TITLE
python YEDDA.py失败

### ISSUE THREAD

**Issue by hzwflyer** [jiesutd/SUTDAnnotator#55]
第一次python YEDDA.py成功，X掉关闭后，再次python YEDDA.py 就报错，是线程或端口占用吗？
YEDDA launched!
OS: Windows
Traceback (most recent call last):
  File "YEDDA.py", line 840, in <module>
    main()
  File "YEDDA.py", line 834, in main
    app = Application(root)
  File "YEDDA.py", line 254, in __init__
    self.readConfig()
  File "YEDDA.py", line 273, in readConfig
    config_dict = json.load(fp)
  File "F:\anaconda\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "F:\anaconda\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "F:\anaconda\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\anaconda\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DreamingFuture** [comment]
是因为你点了，remap把配置文件清空了
